plugins = ["@trivago/prettier-plugin-sort-imports"]
trailingComma = "es5"
tabWidth = 4
semi = true 
singleQuote = true
endOfLine = "lf"
importOrder = ["^components/(.*)$", "^[./]"]
importOrderSeparation = true
importOrderSortSpecifiers = true
